# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Pre-build:
   runs-on: ubuntu-latest
   steps:
     - name: Baixar código fontes
       uses: actions/checkout@v2
      
     - name: Instalar ambiente NodeJs
       uses: actions/setup-node@v2.1.0
       
     - name: Instalar Dependências
       run: npm install
 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Buildando projeto
        run: npm build --prod
        
  Testes:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Testes unitários
        run: ng test --watch=false
      
      - name: Executar Testes de aceitação
        run: ng e2e
